# Generated by Django 4.1.2 on 2022-10-18 04:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid5, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Debito"),
                            (2, "Boleto"),
                            (3, "Financiamento"),
                            (4, "Credito"),
                            (5, "Emprestimo"),
                            (6, "Vendas"),
                            (7, "Ted"),
                            (8, "Doc"),
                            (9, "Aluguel"),
                        ]
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cpf", models.CharField(max_length=11)),
                ("card_number", models.CharField(max_length=12)),
                ("hour", models.TimeField()),
                ("store_owner", models.CharField(max_length=14)),
                ("store_name", models.CharField(max_length=19)),
            ],
        ),
    ]
